config/routes.rb
Rails.application.routes.draw do
  
  resources :lists do
    resources :tasks
  end

  resources :posts do 
    resources :comments  
  end

  resources :facts

  resources :products

  root 'static_pages#home'
  
  devise_for :users
  

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates_presence_of :task_type
  belongs_to :user
  belongs_to :list
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list
  before_action :set_task, except: [:index, :create]

  def index
    @tasks = @list.tasks.sort_by { |task| task.complete ? 1 : 0 }
  end

  def create
    @task = @list.tasks.new(task_params)
    @tasks = current_user.tasks.all
    respond_to do |format|
      if @task.save
        format.html { redirect_to list_tasks_path(@list), notice: 'Post was successfully created.' }  
        format.json { render action: 'index', status: :created, location: @task }
      else
        format.html { render action: 'new' } 
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @task.update(task_params)
    flash.notice = "'#{@task.task_type}' has been Updated!"

    redirect_to list_tasks_path @list
  end

  def destroy
    @task.destroy
    flash.notice = "'#{@task.task_type}' has been Deleted!"

    redirect_to list_tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:task_type, :priority, :duration_in_minutes, :complete, :optimal, :user_id)
  end
end

def set_list
  @list = current_user.lists.find(params[:list_id]) 
end

def set_task
  @task = Task.find(params[:id])
end

app/helpers/tasks_helper.rb
module TasksHelper
  def complete task
    "opaque" if task.complete
  end
  
  def strike_through task 
    task.complete ? "strike-through " : ""
  end

  def task_duration task
    task.duration_in_minutes.blank? ? "" : "#{task.duration_in_minutes} minutes" 
  end
end

app/views/tasks/_form.html.erb
<div class="form"> 
  <%= form_for [@list, Task.new] do |f| %> 
    <%= f.text_field :task_type, placeholder: "add a task" %><br/><br/>    
    <%= f.label :priority %><br/>
    <div class="stars"><%= f.hidden_field :priority, class: "rating" %></div>
    <%= f.hidden_field :complete, value: false %>
    <%= f.hidden_field :optimal, value: false %><br/>
    <%= f.label :duration_in_minutes %><br/>
    <%= f.text_field :duration_in_minutes, id: "duration", readonly: true %><br/>
    <div id="slider-range-max1"></div><br/>
  <%= f.submit %>
  <% end %> 
</div>

app/views/tasks/edit.html.erb
<h1 class="title">Edit</h1>
<div class="form"> 
<%= form_for @task do |f| %>     
  <%= f.text_field :task_type, placeholder: "add a task" %><br/><br/>
  <%= f.label :duration_in_minutes %><br/>
  <%= f.text_field :duration_in_minutes, id: "duration", readonly: true %><br/>
  <div id="slider-range-max1"></div><br/>
    <%= f.label :priority %><br/>
    <%= f.text_field :priority, id: "amount", readonly: true %><br/>
    <%= f.hidden_field :complete, value: false %>
    <%= f.hidden_field :optimal, value: false %>
  <div id="slider-range-max2"></div><br/>
  <%= f.submit %>
<% end %> 
</div>

app/views/tasks/index.html.erb
<h1 class="title"><%= @list.title %><br/><span class="title-description">{ created on <%= @list.created_at.strftime("%B %d, %Y") %> }</span></h1>
<%= render 'lists/sidebar_left' %>
<%= render 'lists/sidebar_right' %>
<div class="row" id="content">
  <div class="col-md-offset-1 col-md-10"> 
    <%= link_to "add a task", '#', class: "links create-link" %>
    <div class="hidden-form-container"><%= render 'tasks/form' %></div><br/><br/>
    <% @tasks.each do |task| %>
    <ul class="list-group <%= complete(task)%>">
      <li class="list-group-item">
        <%= form_for [@list, task] do |f| %> 
          <h3>
            <%= f.check_box :complete, class: "complete-check-box" %>
            <%= f.label :complete, task.task_type, class:(strike_through(task) + "task-label")%>
            <%= link_to "X", [@list, task], class: "links x-for-delete", method: :delete, data: {confirm: "you sure you want to delete this task?"} %> 
          </h3>
          <h4 class="italic"><%= task_duration task%></h4>
          <footer class="footer ">
            <div class="stars"><%= f.hidden_field :priority, class: "rating" %></div>
          </footer>
        <% end %>
        </li>
      </ul>
    <% end %>
    <%= link_to "back", lists_path, class: "links" %>
  </div>
</div>








    
      