config/routes.rb
Rails.application.routes.draw do
  
  resources :lists do
    resources :tasks
  end

  resources :posts do 
    resources :comments  
  end

  resources :facts

  resources :products

  root 'static_pages#home'
  
  devise_for :users
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :title, :price, :description, :stock
  belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper
  before_action :authenticate_user!
  before_action :set_product, except: [:index, :new, :create]
 

  def index
    @products = current_user.products.all
    @product = current_user.products.new
  end


  def show
  end

 
  def new
    @product = Product.new
  end

  
  def edit
  end

  
  def create
    @product = current_user.products.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :index, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :price, :description, :image_url, :stock)
  end
      
end

app/helpers/products_helper.rb
module ProductsHelper
  
  def print_price(price)
    number_to_currency price
  end

  def print_stock stock
    number_with_delimiter stock  
  end
end

app/views/products/_form.html.erb
<div class="input-group">
  <%= form_for @product do |f| %>
    <%= f.text_field :title, placeholder: "title", class:'form-control', class:'form-control' %><br/><br/>
    <%= f.text_area :description, placeholder: "description", class:'form-control' %><br/><br/>
    <%= f.number_field :price, placeholder: "price", step: 'any', class:'form-control' %><br/><br/>
    <%= f.number_field :stock, placeholder: "stock", class:'form-control' %><br/><br/>
    <%= f.submit %><br/><br/>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="container">
  <div class="form">
    <h1>Edit</h1>
    <%= render partial: 'form' %>
    <%= link_to "<< Back ", products_path, class: "links" %><br/>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="products-index">
    <h1 class="title">InventoryTracker<br/><span class="title-description">{ a clean and efficient approach to managing inventory }</span></h1>
    <%= link_to "create a new product", '#', class: "links create-link" %>
    <div class="hidden-form-container"><%= render 'products/form' %></div>
    <table id="product-table" class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <h2>All Products</h2>
          <th>Title</th>
          <th>Description</th>
          <th>Price</th>
          <th>Stock</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tfoot>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Actions</th>
            </tr>
      </tfoot>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td>
              <span class="product-title"><%= product.title %></span>
            </td>
            <td>
              <span class="product-description"><%= product.description %></span>
            <td>
              <span class="product-price"><%= print_price(product.price) %></span>
            </td>
            <td>
              <%= print_stock(product.stock) %>
            </td>
            <td>
              <div class="links">
                <%= link_to "| Edit |", edit_product_path(product)  %>
                <%= link_to "| Delete |", product, method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/products/show.html.erb
<div class="container"> 
  <div class="show-product">
    <h1><%= @product.title %></h1>
    <br/>
    <p><%= @post.body %></p>
    <%= link_to "Delete", @post, method: :delete, data: {confirm: "You sure you want to delete this post?"}, class: "links" %>
    <%= link_to "Edit", edit_post_path(@post), class: "links" %><br/>
    <%= link_to "<<back", posts_path, class: "links" %>
</div>