config/routes.rb
Rails.application.routes.draw do
  
  resources :lists do
    resources :tasks
  end

  resources :posts do 
    resources :comments  
  end

  resources :facts

  resources :products

  root 'static_pages#home'
  
  devise_for :users
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :user_name, :body
  belongs_to :post
end

app/models/fact.rb
class Fact < ActiveRecord::Base
  validates_presence_of :question, :answer
  validates :question, length: { maximum: 350 }
  belongs_to :user
end

app/models/list.rb
class List < ActiveRecord::Base
  validates_presence_of :title
  belongs_to :user
  has_many :tasks
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :body
  belongs_to :user
  has_many :comments
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :title, :price, :description, :stock
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates_presence_of :task_type
  belongs_to :user
  belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :products
  has_many :tasks
  has_many :facts
  has_many :lists

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/comments_controller.rb
  class CommentsController < ApplicationController
  include CommentsHelper
  
  def create
    post = Post.find(params[:post_id ])
    comment = post.comments.create(comment_params)
    
    redirect_to post_path(comment.post)
  end

  private
   def comment_params
    params.require(:comment).permit(:user_name, :body)
  end
end

  

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @facts = current_user.facts
    @fact = current_user.facts.new
  end

  def new
    @fact = Fact.new
  end

  def create
    @fact = current_user.facts.new(fact_params)
    respond_to do |format|
      if @fact.save
        format.html { redirect_to facts_path, notice: 'flip card was successfully created.' }
        format.json { render action: 'index', status: :created, location: @fact }
      else
        format.html { render action: 'new' }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @fact = Fact.find(params[:id])
  end

  private
  def fact_params
    params.require(:fact).permit(:question, :answer)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
   before_action :authenticate_user!
  
  def index
    @lists = current_user.lists
    @task = current_user.tasks.new
  end

  def create
    @list= current_user.lists.new(list_params)
    respond_to do |format|
      if @list.save
        format.html { redirect_to list_tasks_path(@list), notice: 'ToDo list was successfully created.' }  
        format.json { render action: 'index', status: :created, location: @list }
      else
        format.html { render action: 'new' } 
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list = List.find(params[:id])
    flash.notice = "'#{@list.title}' has been Deleted!"
    @list.destroy

    redirect_to lists_path
  end

  private
  def list_params
    params.require(:list).permit(:title, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper
  require 'will_paginate/array'
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, except: [:index, :create]
  
  def index
    @posts = Post.all
    @post = Post.new
    @posts = @posts.sort_by(&:created_at).reverse.paginate(:page => params[:page], :per_page => 4)
  end

  def show
    @posts = Post.all
    @comments = @post.comments
    @comment = Comment.new
  end

  def create
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    flash.notice = "'#{@post.title}' has been Deleted!"

    redirect_to posts_path
  end

  def update
    if current_user == @post.user
      @post.update(post_params)
      flash[:success] = "'#{@post.title}' has been Updated!"
      redirect_to post_path(@post)
    else
      flash[:error] = "You cannot edit other authors' posts!"
      redirect_to posts_path
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:author, :title, :body)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list
  before_action :set_task, except: [:index, :create]

  def index
    @tasks = @list.tasks.sort_by { |task| task.complete ? 1 : 0 }
  end

  def create
    @task = @list.tasks.new(task_params)
    @tasks = current_user.tasks.all
    respond_to do |format|
      if @task.save
        format.html { redirect_to list_tasks_path(@list), notice: 'Post was successfully created.' }  
        format.json { render action: 'index', status: :created, location: @task }
      else
        format.html { render action: 'new' } 
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @task.update(task_params)
    flash.notice = "'#{@task.task_type}' has been Updated!"

    redirect_to list_tasks_path @list
  end

  def destroy
    @task.destroy
    flash.notice = "'#{@task.task_type}' has been Deleted!"

    redirect_to list_tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:task_type, :priority, :duration_in_minutes, :complete, :optimal, :user_id)
  end
end

def set_list
  @list = current_user.lists.find(params[:list_id]) 
end

def set_task
  @task = Task.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type]
  end
 
  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert alert-dismissible #{bootstrap_class_for(msg_type.to_sym)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  
  def print_price(price)
    number_to_currency price
  end

  def print_stock stock
    number_with_delimiter stock  
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def complete task
    "opaque" if task.complete
  end
  
  def strike_through task 
    task.complete ? "strike-through " : ""
  end

  def task_duration task
    task.duration_in_minutes.blank? ? "" : "#{task.duration_in_minutes} minutes" 
  end
end

app/views/layouts/_footer.html.erb
<div class="footer navbar-fixed-bottom">
  <nav>
    <ul>
      <li>MISCELLANY |  <%= link_to "Samantha Jaromirski", 'https://github.com/SamanthaJ' %></li>
    </ul>
  </nav>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MISCELLANY", root_path, id: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Blogger", posts_path%></li>
        <li><%= link_to "TaskManager", lists_path %></li>
        <li><%= link_to "InventoryTracker", products_path %></li>
        <li><%= link_to "FactFlipper", facts_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to current_user.email, edit_user_registration_path %></li>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign in", new_user_session_path%></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miscellany</title>
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= flash_messages %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>